"""consumables

Revision ID: 164c7ced5306
Revises: 8360aba56e01
Create Date: 2023-08-21 12:16:10.040220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '164c7ced5306'
down_revision: Union[str, None] = '8360aba56e01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service', sa.String(length=20), nullable=False),
    sa.Column('staff', sa.String(length=150), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['service'], ['services.code'], ),
    sa.ForeignKeyConstraint(['staff'], ['staff.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consumables')
    # ### end Alembic commands ###
