"""consumables nullable tech

Revision ID: 41ad81f30a30
Revises: 77c6160bb92b
Create Date: 2023-09-08 17:03:30.419217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41ad81f30a30'
down_revision: Union[str, None] = '77c6160bb92b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumables', schema=None) as batch_op:
        batch_op.alter_column('staff',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumables', schema=None) as batch_op:
        batch_op.alter_column('staff',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    # ### end Alembic commands ###
