"""salary fix

Revision ID: 4ac969d85bcd
Revises: 8fff20c49a09
Create Date: 2023-08-12 11:25:05.107854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ac969d85bcd'
down_revision: Union[str, None] = '8fff20c49a09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salary', sa.Column('fix', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salary', 'fix')
    # ### end Alembic commands ###
