"""salary cascade 3

Revision ID: 4eb4064f85aa
Revises: 2fcf3e0ec792
Create Date: 2023-08-22 22:09:04.532088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eb4064f85aa'
down_revision: Union[str, None] = '2fcf3e0ec792'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
