"""consumables deuplicates

Revision ID: 7f449925422c
Revises: 41ad81f30a30
Create Date: 2023-09-08 17:05:04.501335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f449925422c'
down_revision: Union[str, None] = '41ad81f30a30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumables', schema=None) as batch_op:
        batch_op.drop_constraint('staff_service_uc', type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumables', schema=None) as batch_op:
        batch_op.create_unique_constraint('staff_service_uc', ['staff', 'service'])

    # ### end Alembic commands ###
