"""salary

Revision ID: 8fff20c49a09
Revises: c7413a8fa71d
Create Date: 2023-08-12 11:24:46.887126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fff20c49a09'
down_revision: Union[str, None] = 'c7413a8fa71d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salary', 'fix')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salary', sa.Column('fix', sa.FLOAT(), nullable=False))
    # ### end Alembic commands ###
