"""remove unique from bonus

Revision ID: 95670083a159
Revises: bc7740a41112
Create Date: 2023-12-16 10:53:39.801752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95670083a159'
down_revision: Union[str, None] = 'bc7740a41112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bonuses', schema=None) as batch_op:
        batch_op.drop_constraint('staff_dates_uc', type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bonuses', schema=None) as batch_op:
        batch_op.create_unique_constraint('staff_dates_uc', ['staff', 'date_begin', 'date_end'])

    # ### end Alembic commands ###
