"""service_sp_fp

Revision ID: a0e7a8bd59a0
Revises: 95670083a159
Create Date: 2023-12-20 19:33:02.719370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0e7a8bd59a0'
down_revision: Union[str, None] = '95670083a159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fp', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sp', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('sp')
        batch_op.drop_column('fp')

    # ### end Alembic commands ###
