"""consumables constraints

Revision ID: c388edeba472
Revises: 45084e9e4071
Create Date: 2023-08-22 13:46:14.812886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c388edeba472'
down_revision: Union[str, None] = '45084e9e4071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumables', schema=None) as batch_op:
        batch_op.create_unique_constraint('staff_service_uc', ['staff', 'service'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumables', schema=None) as batch_op:
        batch_op.drop_constraint('staff_service_uc', type_='unique')

    # ### end Alembic commands ###
