"""salary fix

Revision ID: d4ea644ecc9e
Revises: d70cd50bcec2
Create Date: 2023-08-12 11:29:50.033528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4ea644ecc9e'
down_revision: Union[str, None] = 'd70cd50bcec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salary', sa.Column('fix', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salary', 'fix')
    # ### end Alembic commands ###
