"""salary fix

Revision ID: d70cd50bcec2
Revises: 4ac969d85bcd
Create Date: 2023-08-12 11:29:34.088433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd70cd50bcec2'
down_revision: Union[str, None] = '4ac969d85bcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salary', 'fix')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salary', sa.Column('fix', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###
