"""salary filial

Revision ID: fd56b0a88c34
Revises: 085975fc9fbe
Create Date: 2023-10-06 15:45:08.539025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd56b0a88c34'
down_revision: Union[str, None] = '085975fc9fbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filial', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key('filial_id', 'filials', ['filial'], ['name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salary', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('filial')

    # ### end Alembic commands ###
