"""service is_submit nullable

Revision ID: fd62b16e9cf4
Revises: c388edeba472
Create Date: 2023-08-22 13:50:03.978103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd62b16e9cf4'
down_revision: Union[str, None] = 'c388edeba472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('is_submit',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('is_submit',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
